export const ProjectsData = [
  {
    id: 1,
    img: "./images/Project/wedding.png",
    langs: ["HTML", "CSS", "BOOTSTRAP"],
    title: "Studio Wedding",
    desc: "Provide all kinds of wedding services",
    link: "https://tntann.github.io/studio_wedding/",
  },
  {
    id: 2,
    img: "./images/Project/shopee.png",
    langs: ["HTML", "CSS", "Reponsive"],
    title: "Shopee Clone",
    desc: "Shoppee clone UI only",
    link: "https://tntann.github.io/shopee_clone/",
  },
  {
    id: 3,
    img: "./images/Project/music-app.png",
    langs: ["HTML", "CSS", "JAVASCRIPT"],
    title: "Music Player",
    desc: "Minimal design, Working basic functions",
    link: "https://tntann.github.io/music_player/",
  },
  {
    id: 4,
    img: "./images/Project/firstweb.png",
    langs: ["HTML", "CSS", "Reponsive"],
    title: "My First Website",
    desc: "Very first website clone",
    link: "https://tntann.github.io/my-first-web/",
  },
  {
    id: 5,
    img: "./images/Project/shopphone.png",
    langs: ["HTML", "CSS", "MySQL", "PHP"],
    title: "Ecommerce",
    desc: "Minimal design, Working basic functions",
    link: "https://hecommercestore.000webhostapp.com/",
  },
  {
    id: 6,
    img: "./images/Project/portfolio.png",
    langs: ["REACTJS", "TAILWINDCSS", "Responsive"],
    title: "Portfolio",
    desc: "My portfolio",
    link: "https://portfolio-reactjs-tntan.vercel.app/",
  },
];
